name: Installers

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1    
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Validate Installations
        run: |
          python --version
          node --version
          java -version
          go version

      - name: Lint with flake8
        run: |
          pip install flake8

      - name: Save flake8 report
        run: |
          flake8 . --count --verbose --statistics > flake8-report.txt || true

      - name: Upload flake8 report
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: flake8-report.txt


