name: Build and Run Static Apps

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-static-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install http-server
        run: npm install -g http-server

      - name: Build Prime Checker
        run: |
          mkdir -p build/prime-checker
          cp -r prime-checker/public/* build/prime-checker/

      - name: Build Calculator
        run: |
          mkdir -p build/calculator
          cp -r calculator-app/public/* build/calculator/

      - name: Start Prime Checker (Port 8080)
        run: |
          nohup http-server ./build/prime-checker -p 8080 > prime.log 2>&1 &

      - name: Start Calculator (Port 8081)
        run: |
          nohup http-server ./build/calculator -p 8081 > calc.log 2>&1 &

      - name: Wait for Servers to Start
        run: sleep 5

      - name: Verify Prime Checker is Running
        run: curl -I http://localhost:8080 | grep "200 OK"

      - name: Verify Calculator is Running
        run: curl -I http://localhost:8081 | grep "200 OK"

      - name: Output Logs
        run: |
          echo "::group::Prime Checker Log"
          cat prime.log
          echo "::endgroup::"

          echo "::group::Calculator Log"
          cat calc.log
          echo "::endgroup::"
